### ISSUE TITLE
Issue with app selection

### ISSUE THREAD

**Issue by blackxored** [deanishe/alfred-vpn-manager#5]
```
F00E-423F-8AD2-90260BC58C87/workflow/workflow.py", line 2067, in run
    func(self)
  File "./vpn.py", line 534, in main
    return do_config(args.get('<query>'))
  File "./vpn.py", line 342, in do_config
    icon=app.info.path,
AttributeError: 'NoneType' object has no attribute 'path'
```
Fixed naively by commenting all info.paths since I didn't quite care about the icon, just wanted to select Tunnelblick.

**Comment by deanishe** [comment]
Sorry about that. Fixed in [v3.0.1](https://github.com/deanishe/alfred-vpn-manager/releases/tag/v3.0.1).

The code I was using only worked with running apps, and of course I had both Tunnelblick and Viscosity running for testing the workflow…
